[package]
name = "docker4rs"
version = "0.0.0"
authors = ["Arthur Asatryan <biacoder@gmail.com>"]
description = "Docker REST API implementation"
documentation = "https://docs.rs/docker4rs"
homepage = "https://github.com/Biacode/docker4rs"
repository = "https://github.com/Biacode/docker4rs"
keywords = ["docker", "rest", "api", "client"]
readme = "README.md"
license = "Apache-2.0"
exclude = [
    ".travis.yml",
    ".gitignore",
]

[lib]
name = "docker4rs"
path = "src/lib.rs"

[dependencies]
hyper = "0.9"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
log = "0.3"
