[package]
name = "docker4rs-tcp"
version = "0.0.1"
authors = ["Arthur Asatryan <biacoder@gmail.com>"]
workspace = "../"

[lib]
name = "docker4rs_tcp"
path = "src/lib.rs"

[dependencies]
docker4rs-core = { path = "../docker4rs-core" }